SELECT `Continent`, 
`Region`, 
`SurfaceArea`, 
`IndepYear`, 
`Population`, 
`LifeExpectancy`, 
`GNP`, 
`GNPOld`, 
`LocalName`, 
`GovernmentForm`, 
`HeadOfState`, 
`Capital`, 
`Code2`, 
`Code`, 
`Name` 
FROM `world`.`country`;